### ISSUE TITLE
Support switching between multiple queues

### ISSUE THREAD

**Issue by jserv** [sysprog21/lab0-c#101]
In conjunction with LeetCode [23. Merge k Sorted Lists](https://leetcode.com/problems/merge-k-sorted-lists/), we have to revisit the current command line interpreter. In particular, the following commands should be added or revised.
* `show` : Show the current queue ID and its contents.
* `prev` : Show the previous queue ID
* `next` : Show the next queue ID

The existing commands should perform on the current queue accordingly. After the above is completed, new command `merge` can be introduced. Consider the command sequence below:
```
new
ih RAND 10
sort
new
ih RAND 9
sort
new
ih RAND 8
sort
merge
```

Three queues are present before the command `merge`, and one queue is left as a result of its execution. Before performing `merge`, we should go through each queue to check if every queue is sorted in advance.

**Comment by eecheng87** [comment]
We can chain multiple queues into a circular "queue-list". However, there is no mechanism for operating the previous queue after `new` is posted. Thus, I suppose `prev` would replace current queue with the previous one, rather than show the previous queue ID. For the same reason, `next` would replace current queue with the next one. 

Does it make sense?

**Comment by jserv** [comment]
> We can chain multiple queues into a circular "queue-list". However, there is no mechanism for operating the previous queue after `new` is posted. Thus, I suppose `prev` would replace current queue with the previous one, rather than show the previous queue ID. For the same reason, `next` would replace current queue with the next one.

I like the idea of meta-queue, which maintains the chain of queues. If we want to implement [23. Merge k Sorted Lists](https://leetcode.com/problems/merge-k-sorted-lists/) in this fashion, what do we need to proceed?

**Comment by eecheng87** [comment]
Obviously, we need those three new command you mentened. Besides, additional global variable for the chain of queues is needed. Other minor changes are required since `l_meta` might be replaced. 

I'll draft the changes later.
