### ISSUE TITLE
Pre-push.hook check bug on validating repository

### ISSUE THREAD

**Issue by vax-r** [sysprog21/lab0-c#151]
## Summary
When we made some modification to the content and trying to `git push` the changes to our remote repository, `/scripts/pre-push.hook` present a stage for validation of the repository.
It tries to get a specific commit hash number with git log message pattern matching "^Bump copyright" using the following command
```
commit=$(git rev-list -n 1 --grep '^Bump copyright' 1aca5b98471765db50c91e03298e49bf7c08cdbc...HEAD)
```
The value of `commit` is expected to be "3ed17237af5b1ead6c394df5099bc2bc1f8392df".
However, since you have another git commit which is "Merge pull request #150 from sysprog21/bump-copyright-year".
Its commit message also matches the pattern of `^Bump copyright`, so the command mentioned above for getting the value of `commit` will make the value of `commit` result in `390ade9eca44b432acb758084e7122cc2c46e485`.
This behavior will cause the pre-hook checking stage to fail.

*I am not sure the bug is only for me locally or it's truly a bug needed to be fixed.*

## Expected
`commit` should be `3ed17237af5b1ead6c394df5099bc2bc1f8392df`

## Possible fixup
Change line 15 of `pre-push.hook` to the following command
```
commit=$(git rev-list --skip 1 --grep '^Bump copyright' 1aca5b98471765db50c91e03298e49bf7c08cdbc...HEAD)
```

**Comment by jserv** [comment]
> ## Possible fixup
> Change line 15 of `pre-push.hook` to the following command
> ```
> commit=$(git rev-list --skip 1 --grep '^Bump copyright' 1aca5b98471765db50c91e03298e49bf7c08cdbc...HEAD)
> ```

It sounds great. Please send a pull request.
