### ISSUE TITLE
Inconsistent Cppcheck Version Leads to Differing Default Enabled Checking Flags

### ISSUE THREAD

**Issue by 25077667** [sysprog21/lab0-c#153]
## Environment

- **Cppcheck Versions**: Discrepancy between Cppcheck 2.7 (Docker, Ubuntu 22.04) and Cppcheck 2.12.0 (Host, Archlinux)
- **Operating Systems**: Ubuntu 22.04 (Docker) vs. Archlinux (Host)
- **Issue Context**: Encountered during execution of a git pre-commit hook.

## Issue Description

The project encounters differing static analysis results when committing changes, triggered by the git pre-commit hook using `cppcheck`. The root cause appears to be the version difference between the Cppcheck tool in my Docker environment (version 2.7) and on my host system (version 2.12.0), leading to varying default enabled checking flags.

### Encountered Issues

- Different `cppcheck` warnings and errors are reported due to the version discrepancy.
- These include suggestions for declaring parameters as pointers to const, an error about returning a pointer to a local variable, style recommendations, and a notice on limited value flow analysis.

## Proposed Solution

To address this issue and achieve consistent static analysis checks across environments, I have implemented specific changes in the codebase and the static analysis configuration.

### Changes Made

1. **Code Adjustments**: Updated function parameters from `char *` to `const char *` where appropriate to align with `cppcheck` recommendations, enhancing code safety and maintainability.
2. **Pre-commit Hook Script Update**: Modified the `scripts/pre-commit.hook` to include new suppressions (`returnDanglingLifetime`, `constParameterCallback`, `constParameterPointer`) and added `--check-level=exhaustive` to the `cppcheck` options for a thorough analysis.

### Implementation Details

The modifications involve:
- Making parameters `const` in several functions across `report.c` and `report.h` files to prevent unintended modifications.
- Adjusting the pre-commit hook to tailor the `cppcheck` analysis, reducing false positives and focusing on relevant issues.
- See: https://github.com/25077667/lab0-c/commit/673f5a1559d97cc0ab542ee8c0291fc11c101a30

### Expected Outcome

With these changes, we expect to:
- Harmonize static analysis checks across different `cppcheck` versions, reducing inconsistencies.
- Improve code quality by adhering to best practices recommended by static analysis.
- Streamline the development process by minimizing disruptive and differing analysis outcomes between environments.

## Request for Feedback

I've proposed a solution that seems to address the observed issues effectively. However, I welcome any feedback or suggestions for improvement from the community. Specifically:
- Are there better approaches to ensure `cppcheck` version consistency across environments?
- Feedback on the proposed suppressions and `cppcheck` configuration adjustments.

Your insights and suggestions will be invaluable in refining this solution and ensuring our static analysis process is as robust and consistent as possible.

**Comment by 25077667** [comment]
`--suppress=returnDanglingLifetime:report.c` in pre-commit.hook might be a bug for cppcheck.

It is indicating the `ss` is returnDanglingLifetime:
```c
char *strsave_or_fail(const char *s, const char *fun_name)
{
    if (!s)
        return NULL;

    size_t len = strlen(s);
    check_exceed(len + 1);
    char *ss = malloc(len + 1);
    if (!ss)
        fail_fun("strsave failed in %s", fun_name);

    allocate_cnt++;
    allocate_bytes += len + 1;
    current_bytes += len + 1;
    peak_bytes = MAX(peak_bytes, current_bytes);
    last_peak_bytes = MAX(last_peak_bytes, current_bytes);

    return strncpy(ss, s, len + 1);
}
```

Actually, it's a pointer to malloced chunk. This error message from cppcheck should be a false positive alert.

**Comment by jserv** [comment]
> Adjusting the pre-commit hook to tailor the cppcheck analysis, reducing false positives and focusing on relevant issues.
See: https://github.com/25077667/lab0-c/commit/673f5a1559d97cc0ab542ee8c0291fc11c101a30

You utilize the option `--check-level`, which is introduced in Cppcheck v2.11. Can you eliminate it?

**Comment by 25077667** [comment]
@jserv, what do you think about introducing an additional check to verify whether the cppcheck version is greater than 2.11?

**Comment by 25077667** [comment]
What do you think about this change:
https://github.com/25077667/lab0-c/commit/d8821504c439723c196d74162b7d1961310d0146

**Comment by jserv** [comment]
> What do you think about this change: [25077667@d882150](https://github.com/25077667/lab0-c/commit/d8821504c439723c196d74162b7d1961310d0146)

It looks great. Please send a pull request.
