### ISSUE TITLE
On bash 5.0.3 pre commit hook fails

### ISSUE THREAD

**Issue by owlfox** [sysprog21/lab0-c#24]
debian 10, bash 5.0.3 
```bash
$ git commit -m "a bad one"
.git/hooks/commit-msg: line 157: v: invalid indirect expansion
```
tried on bash 4.4, looks okay

Not sure how to make it work on both version at the moment

**Comment by jserv** [comment]
Can you print `${!v}` around line 156 with bash 4.4?

**Comment by owlfox** [comment]
`echo "{!v}:"${!v}`
it is empty in 4.4
while in 5.0 it dies with error message mentioned above

Not sure what's this !v doing here.
