### ISSUE TITLE
harness.c could not pass the static analysis

### ISSUE THREAD

**Issue by Nienzu** [sysprog21/lab0-c#4]
I encounter the error message when running `cppcheck 1.84` to `harness.c`.
```
$ : cppcheck harness.c
Checking harness.c ...
[harness.c:148]: (error) Address of auto-variable 'new_block->payload' returned
```
There may be two solutions: 
1. [amikai's note](https://hackmd.io/s/rkyPtw_YQ#Queue-implementation)
2. add `printf` to print the pointer of `p`
```C

void *p = (void *) &new_block->payload;
memset(p, FILLCHAR, size);
printf("%p\n", p);  
...
...
...
return p;
```

**Comment by jserv** [comment]
@Nienzu, It was meant to be alterted by cppcheck or something similar.

**Comment by Nienzu** [comment]
Yes, I know it's altered by cppcheck. Then it ends up with not being allowed to commit. So I think my question is:
1.  Should this issue be fixed? 
2.  Is "p" an automatic variable when assigned with an allocated object?
