### ISSUE TITLE
Add aspell-en package in prerequisites

### ISSUE THREAD

**Issue by asas1asas200** [sysprog21/lab0-c#78]
Aspell-en is a "recommend" package in Ubuntu, so it will be installed with aspell package.
But in other distros like Arch, it won't auto install, and terminal will output error by below when I commit:
```
Error: No word lists can be found for the language "en".
```
But I can still commit successfully with this error.

So I think that should be added in readme or adding a protect in pre-commit hook.

**Comment by jserv** [comment]
Can you improve the pre-commit hook for checking `/usr/lib/aspell/en*.rws`? Alternatively, you can contribute the notice for Arch Linux.

**Comment by asas1asas200** [comment]
I will try it.
