### ISSUE TITLE
It can use VLA to bypass the memory allocating limit in q_sort()

### ISSUE THREAD

**Issue by asas1asas200** [sysprog21/lab0-c#80]
In `q_sort()`, it prefered to use a in-place algorithm to sort the list, so it disallowed the `malloc()` in some testcases.

But I can still use [Variable-length array](https://en.wikipedia.org/wiki/Variable-length_array) to bypass this limit, and use a algorithm which space complexity is O(n) to pass all testcases.

Is it a fatal problem?

**Comment by jserv** [comment]
@eecheng87, we can follow [the way how Linux kernel removed VLA](https://www.phoronix.com/scan.php?page=news_item&px=Linux-Kills-The-VLA). That is, enforce compilation argument `-Wvla`.
