### ISSUE TITLE
Moving q_release_element into queue.h cause free error

### ISSUE THREAD

**Issue by laneser** [sysprog21/lab0-c#86]
When q_release_element called from qtest.c,
the free is not test_free, because qtest.c use regular malloc/free.
Then it raise error: munmap_chunk(): invalid pointer 

If the q_release_element always free memories from queue.c,
Then, change code to (need `#include "harness.h"`)
```c
static inline void q_release_element(element_t *e)
{
    test_free(e->value);
    test_free(e);
}
```

can fix the issue.

Otherwise, we have to move `q_release_element` back to queue.c.
Or, define `q_release_element_qtest` version for qtest usage.

**Comment by kevinshieh0225** [comment]
I found the same bug of munmap_chunk(). Thanks for @laneser suggestion, the bug has fixed! 
I am curious why the change of the header function will cause the bug?
and why using test_free from "harness.h" can fix it?
It took me a night but still can't figure out the reason of it.

**Comment by jserv** [comment]
@laneser, Can you send the proposed change as a pull request? So that, @eecheng87 would reproduce and confirm.

**Comment by laneser** [comment]
> I found the same bug of munmap_chunk(). Thanks for @laneser suggestion, the bug has fixed! I am curious why the change of the header function will cause the bug? and why using test_free from "harness.h" can fix it? It took me a night but still can't figure out the reason of it.

Because free is redefined as test_free in queue.c , and defined as free in qtest.c.

When q_release_element move to queue.h, ref to https://gcc.gnu.org/onlinedocs/gcc/Inline.html, inline substitution may cause it become free in qtest.c , and test_free in queue.c.

And the malloc function is defined as test_malloc in queue.c , when qtest.c call q_release_element to free the pointer which returned by test_malloc, it make munmap_chunk(): invalid pointer.

**Comment by eecheng87** [comment]
Thanks for @laneser 's solution!
